import React from 'react';
import { Helmet } from 'react-helmet-async';
import '../index.css';

function Terms() {
    return (
        <>
            <Helmet>
                <title>Terms of Use - Daily Brief Newsly</title>
                <meta name="description" content="Terms of Use for Daily Brief Newsly - Understand the terms and conditions for using our news platform." />
                <meta name="keywords" content="terms of use, terms and conditions, Daily Brief Newsly, user agreement" />
            </Helmet>

            <div className="page-container">
                <div className="page-hero">
                    <h1 className="page-title">Terms of Use</h1>
                    <p className="page-subtitle">Guidelines for Using Our Platform</p>
                </div>

                <div className="content-card">
                    <div className="card-header">
                        <h2>Terms of Use</h2>
                    </div>

                    <div className="card-content">
                        <p>
                            Welcome to daily.briefnewsly.org. By accessing our website, you agree to the following terms:
                        </p>

                        <div className="mission-section">
                            <h3 className="section-title">1. Content Usage:</h3>
                            <p className="mission-text">
                                We do not host full articles. We curate and summarize content from external RSS sources,
                                crediting each source and linking to their original pages. Our summaries and headlines are
                                generated by AI to enhance readability.
                            </p>
                        </div>

                        <div className="how-it-works-section">
                            <div className="steps-container">
                                <div className="step-item">
                                    <div className="step-icon">2</div>
                                    <div className="step-content">
                                        <h4>Copyright</h4>
                                        <p>All copyrights remain with the original publishers. If you are a content owner and believe your work is misrepresented, please reach out at support@briefnewsly.org.</p>
                                    </div>
                                </div>

                                <div className="step-item">
                                    <div className="step-icon">3</div>
                                    <div className="step-content">
                                        <h4>Liability</h4>
                                        <p>We do our best to ensure accuracy but do not guarantee the completeness or reliability of the summarized content. Users should verify details from the original source linked.</p>
                                    </div>
                                </div>

                                <div className="step-item">
                                    <div className="step-icon">4</div>
                                    <div className="step-content">
                                        <h4>Prohibited Use</h4>
                                        <p>Do not attempt to reverse-engineer, scrape, or exploit the data presented on this site.</p>
                                    </div>
                                </div>

                                <div className="step-item">
                                    <div className="step-icon">5</div>
                                    <div className="step-content">
                                        <h4>Ads and Monetization</h4>
                                        <p>We display third-party ads (e.g., Google AdSense). We are not responsible for the content of external ads.</p>
                                    </div>
                                </div>

                                <div className="step-item">
                                    <div className="step-icon">6</div>
                                    <div className="step-content">
                                        <h4>Changes to Terms</h4>
                                        <p>We reserve the right to modify these terms at any time.</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="closing-section">
                            <p className="closing-text">
                                By using our website, you acknowledge that you have read and understood these terms and agree to be bound by them.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}

export default Terms;
